language: node_js
node_js:
  - 9

cache:
  directories:
    - "node_modules"

env:
  - WEB_INDEX=.vuepress/dist/index.html

install:
  - yarn
  - yarn upgrade

script:
  - yarn build
  - test -f $WEB_INDEX -a -s $WEB_INDEX

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  email: jimmy.dai@program.com.tw
  name: Jimmy.Dai
  on:
    branch: master

notifications:
  email:
    on_failure: always